### ISSUE TITLE
install without admin rights

### ISSUE THREAD

**Issue by trvinh** [BIONF/FAS#2]
Install succeed 
```
$ pip install --user .
Processing /home/vinh/Desktop/programs/bionf/FAS
Installing collected packages: greedyFAS
  Running setup.py install for greedyFAS ... done
Successfully installed greedyFAS-1.0.0
```
but the functions (greedyFAS, annoFAS,...) not found!

**Comment by trvinh** [comment]
the installed package found in `/home/vinh/.local/lib/python2.7/site-packages`

**Comment by ebersber** [comment]
Lieber Vinh,
Läuft das auch unter Python3? Der Support für 2.7 läuft aus!
LG,
ingo

> Am 15.01.2020 um 14:20 schrieb Vinh Tran <notifications@github.com>:
> 
> python2.7

**Comment by trvinh** [comment]
@ebersber : Lieber Ingo,
actually, the annoFAS script only works with python 3 (in case you missed it, I wrote a python script for doing stuffs that related to the feature annotation). The reason why the installed FAS locates in my python2.7 path is, that I've used `pip` for python 2.7 (it's still the default python version of our workstations, isn't it). To get `pip` installed with python3, I think we need our admin.

**Comment by ebersber** [comment]
Ok, dann passt das. Ich hab geschaut, wir haben python3 unter /usr/bin/python3, aber pip scheint wirklich nur pip2 zu sein. Sagst Du Stefan Bescheid?
Danke,
ingo

**Comment by trvinh** [comment]
ja, ich werde Stefan sagen.

**Comment by JuRuDo** [comment]
solved:
export PATH=$HOME/.local/bin:$PATH
needs to be added to the .bashrc
after using pip install with the --user option
