### ISSUE TITLE
filter annotated domains for fas calculation

### ISSUE THREAD

**Issue by trvinh** [BIONF/FAS#24]
further filter domains with a specified evalue cutoff before calculating fas score
the output domain files should also contain only domains that exceed the value cutoff

**Comment by JuRuDo** [comment]
Already implemented. The e-value cutoff is applied twice once during annotation and once before calculation.

**Comment by trvinh** [comment]
check option `-f`, `-i` and `--eFlps`
```
  -f EFEATURE, --eFeature EFEATURE
                        eValue cutoff for PFAM/SMART domain, applied during annotation but also during calculation
  -i EINSTANCE, --eInstance EINSTANCE
                        eValue cutoff for PFAM/SMART instances, applied during annotation but also during calculation
  --eFlps EFLPS         eValue cutoff for fLPS

```
